USB_VID = 0x239A
USB_PID = 0x802A
USB_PRODUCT = "AramCon Badge 2020"
USB_MANUFACTURER = "CodeMagic"

MCU_CHIP = nrf52840

INTERNAL_FLASH_FILESYSTEM = 1
CIRCUITPY_DISPLAYIO = 1

CIRCUITPY_REQUIRE_I2C_PULLUPS = 0
