USB_VID = 0x239A
USB_PID = 0x802A
USB_PRODUCT = "AramCon Badge 2019"
USB_MANUFACTURER = "CodeMagic"

MCU_CHIP = nrf52840

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICE_COUNT = 1
EXTERNAL_FLASH_DEVICES = "GD25Q16C"

CIRCUITPY_DISPLAYIO = 1
